// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Ko0LaXF4AMYQcZeHR5QnYfZFnvjEOUg',
    appId: '1:449305476282:web:515c3d2d8573b72510d683',
    messagingSenderId: '449305476282',
    projectId: 'jhguitartree-953b9',
    authDomain: 'jhguitartree-953b9.firebaseapp.com',
    storageBucket: 'jhguitartree-953b9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaOGi9T51IEFejTc33P9O2afSlJY2ODcM',
    appId: '1:449305476282:android:436130295d4efbb710d683',
    messagingSenderId: '449305476282',
    projectId: 'jhguitartree-953b9',
    storageBucket: 'jhguitartree-953b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkwHKsp_b36upJipSAk693VL45-7eX8vw',
    appId: '1:449305476282:ios:2c91c45669dd4b7e10d683',
    messagingSenderId: '449305476282',
    projectId: 'jhguitartree-953b9',
    storageBucket: 'jhguitartree-953b9.firebasestorage.app',
    iosBundleId: 'com.example.jhGuitarTree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkwHKsp_b36upJipSAk693VL45-7eX8vw',
    appId: '1:449305476282:ios:5fb89f8ff95cad1b10d683',
    messagingSenderId: '449305476282',
    projectId: 'jhguitartree-953b9',
    storageBucket: 'jhguitartree-953b9.firebasestorage.app',
    iosBundleId: 'com.myfirstapp.jhguitartree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Ko0LaXF4AMYQcZeHR5QnYfZFnvjEOUg',
    appId: '1:449305476282:web:858c3c5cbd7a65a410d683',
    messagingSenderId: '449305476282',
    projectId: 'jhguitartree-953b9',
    authDomain: 'jhguitartree-953b9.firebaseapp.com',
    storageBucket: 'jhguitartree-953b9.firebasestorage.app',
  );

}